# Generated by Django 3.1.8 on 2021-06-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_app", "0002_auto_20210601_1914"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
